"""Small maps that ask the reachability gate one question each.

A gate that only ever runs on q2dm1 proves nothing: q2dm1 passes, and a gate
that returned PASS unconditionally would also pass it. What has to be shown is
that each verdict has a case that produces it and a case that does not, and
that the two differ by ONE thing - a door with a targetname, a lift whose
button was never placed, a destination entity that is not in the map.

So these come in pairs wherever a pair is possible, generated by the same
function with one argument changed, and the guard asserts both halves.

Every fixture is a sealed Valve 220 `.map` the pinned compiler will build
without a leak, with at least two player starts, because the question the gate
asks is about players getting to each other.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from mapgen_fixture_lib import (  # noqa: E402
    Box,
    CONTENTS_LAVA,
    CONTENTS_SOLID,
    CONTENTS_WATER,
    Entity,
    MapFixture,
    hollow_room,
)

WALL = "e1u1/c_met5_2"
FLOOR = "e1u1/c_met5_1"
WATER = "e1u1/c_met5_1"


def _spawn(x: float, y: float, z: float) -> Entity:
    return Entity("info_player_deathmatch",
                  keys=[("origin", f"{x:g} {y:g} {z:g}")])


def _floor_with_hole(x0, y0, x1, y1, hx0, hy0, hx1, hy1, z0, z1) -> list[Box]:
    """A slab from (x0,y0) to (x1,y1) with a rectangular hole in it.

    Four boxes rather than one, because a `.map` brush is convex and a slab
    with a hole is not.
    """
    return [
        Box((x0, y0, z0), (x1, hy0, z1), texture=FLOOR),
        Box((x0, hy1, z0), (x1, y1, z1), texture=FLOOR),
        Box((x0, hy0, z0), (hx0, hy1, z1), texture=FLOOR),
        Box((hx1, hy0, z0), (x1, hy1, z1), texture=FLOOR),
    ]


# --------------------------------------------------------------------------
# the control: nothing in the way
# --------------------------------------------------------------------------

def open_room(path: Path) -> None:
    """One room, two starts, no obstacle. The gate must pass this or it is
    broken in a way no other case would show."""
    fx = MapFixture("reach_open_room", "one room, two starts")
    fx.world_brushes = hollow_room((-320, -320, 0), (320, 320, 256),
                                   texture=WALL, floor_texture=FLOOR)
    fx.entities = [_spawn(-192, 0, 32), _spawn(192, 0, 32)]
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a pocket a player can fall into and not climb out of
# --------------------------------------------------------------------------

def _pit(name: str, depth: float, lava: bool) -> MapFixture:
    fx = MapFixture(name, "a room with a pit in the floor")
    inner_lo = (-448, -320, -depth)
    inner_hi = (448, 320, 256)
    fx.world_brushes = list(hollow_room(inner_lo, inner_hi, texture=WALL,
                                        floor_texture=FLOOR))
    # The walkable floor at z=0, with a square hole over the pit.
    fx.world_brushes += _floor_with_hole(-448, -320, 448, 320,
                                         -96, -96, 96, 96, -depth, 0)
    if lava:
        fx.world_brushes.append(
            Box((-96, -96, -depth), (96, 96, -depth + 64), texture=FLOOR,
                contents=CONTENTS_LAVA))
    fx.entities = [_spawn(-320, 0, 32), _spawn(320, 0, 32)]
    return fx


def pocket(path: Path) -> None:
    """A dry pit too deep to jump out of: reachable, non-lethal, no exit.
    The gate must FAIL this - it is the defect the whole gate exists for."""
    fx = _pit("reach_pocket", 192.0, lava=False)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def lava_pit(path: Path) -> None:
    """The same pit with lava in the bottom. Standing there kills, so it is a
    terminal state and the gate must PASS - otherwise no map with lava in it
    could ever pass and the gate would be useless."""
    fx = _pit("reach_lava_pit", 192.0, lava=True)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def step_down(path: Path) -> None:
    """A drop of forty units with a ramp back up. An ordinary piece of level
    design; a gate that calls this a trap cannot be used on anything."""
    fx = MapFixture("reach_step_down", "a low ledge with a way back up")
    fx.world_brushes = list(hollow_room((-448, -320, 0), (448, 320, 256),
                                        texture=WALL, floor_texture=FLOOR))
    # A raised half of the room, and a stair of four steps back onto it.
    fx.world_brushes.append(Box((0, -320, 0), (448, 320, 40), texture=FLOOR))
    for i in range(4):
        fx.world_brushes.append(
            Box((-40 - 40 * i, -64, 0), (0, 64, 40 - 10 * i), texture=FLOOR))
    fx.entities = [_spawn(-320, 0, 32), _spawn(320, 0, 80)]
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# two rooms that cannot see each other
# --------------------------------------------------------------------------

def split(path: Path) -> None:
    """Two sealed rooms, a start in each, nothing between them. Each start can
    reach everything around it, so a search that only asked "can a player get
    out of where he is" would pass this."""
    fx = MapFixture("reach_split", "two rooms, one start each, no way between")
    fx.world_brushes = list(hollow_room((-768, -256, 0), (-256, 256, 224),
                                        texture=WALL, floor_texture=FLOOR))
    fx.world_brushes += hollow_room((256, -256, 0), (768, 256, 224),
                                    texture=WALL, floor_texture=FLOOR)
    fx.entities = [_spawn(-512, 0, 32), _spawn(512, 0, 32)]
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a route that exists only through a door
# --------------------------------------------------------------------------

def _two_rooms_and_a_door(name: str, targetname: str | None) -> MapFixture:
    fx = MapFixture(name, "two rooms joined only by a door")
    fx.world_brushes = list(hollow_room((-512, -128, 0), (512, 128, 192),
                                        texture=WALL, floor_texture=FLOOR))
    # A dividing wall with a doorway 64 wide and 96 tall.
    fx.world_brushes += [
        Box((-16, -128, 0), (16, -32, 192), texture=WALL),
        Box((-16, 32, 0), (16, 128, 192), texture=WALL),
        Box((-16, -32, 96), (16, 32, 192), texture=WALL),
    ]
    keys = [("angle", "-1"), ("lip", "8"), ("speed", "100")]
    if targetname:
        keys.append(("targetname", targetname))
    fx.entities = [
        Entity("func_door", keys=keys,
               brushes=[Box((-16, -32, 0), (16, 32, 96), texture=WALL)]),
        _spawn(-320, 0, 32),
        _spawn(320, 0, 32),
    ]
    return fx


def door(path: Path) -> None:
    """A door anyone can walk up to. The route exists and the gate must pass."""
    fx = _two_rooms_and_a_door("reach_door", None)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def door_locked(path: Path) -> None:
    """The same door with a targetname nothing in the map fires. It looks
    connected on any drawing of the level and it is not."""
    fx = _two_rooms_and_a_door("reach_door_locked", "never_fired")
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def door_button(path: Path) -> None:
    """The same locked door, with a button in the first room that opens it -
    so the route exists, but only to a search that presses the button."""
    fx = _two_rooms_and_a_door("reach_door_button", "the_door")
    fx.name = "reach_door_button"
    fx.entities.insert(1, Entity(
        "func_button",
        keys=[("angle", "0"), ("lip", "4"), ("speed", "40"),
              ("target", "the_door"), ("wait", "3")],
        brushes=[Box((-320, 120, 32), (-288, 128, 64), texture=WALL)]))
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a machine nothing can work, that nothing needs
# --------------------------------------------------------------------------

def _room_with_a_cupboard(name: str, targetname: str | None) -> MapFixture:
    """One room with both starts in it, and a door into a cupboard.

    Nothing is behind that door: no start, no pickup, nowhere to be. So when
    the door is dead the only thing wrong with the map is the door.
    """
    fx = MapFixture(name, "a room with a cupboard in the corner")
    fx.world_brushes = list(hollow_room((-448, -320, 0), (448, 320, 256),
                                        texture=WALL, floor_texture=FLOOR))
    # The cupboard: a walled box in the corner, open on the side the door is.
    fx.world_brushes += [
        Box((256, 128, 0), (288, 320, 256), texture=WALL),
        Box((256, 128, 0), (448, 160, 256), texture=WALL),
        Box((288, 160, 96), (448, 192, 256), texture=WALL),
    ]
    keys = [("angle", "-1"), ("lip", "8"), ("speed", "100")]
    if targetname:
        keys.append(("targetname", targetname))
    fx.entities = [
        Entity("func_door", keys=keys,
               brushes=[Box((288, 160, 0), (448, 192, 96), texture=WALL)]),
        _spawn(-320, 0, 32),
        _spawn(-320, 224, 32),
    ]
    return fx


def cupboard(path: Path) -> None:
    """The cupboard door works. Nobody needs it and the map is fine."""
    fx = _room_with_a_cupboard("reach_cupboard", None)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def cupboard_dead(path: Path) -> None:
    """The same door with a targetname nothing fires. Everything a player
    needs is still where it was, and the map is still refused: a machine no
    player can ever work is a defect on its own."""
    fx = _room_with_a_cupboard("reach_cupboard_dead", "never_fired")
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a route that exists only by lift
# --------------------------------------------------------------------------

def _room_with_a_lift(name: str, targetname: str | None) -> MapFixture:
    fx = MapFixture(name, "a ledge reachable only by lift")
    fx.world_brushes = list(hollow_room((-384, -192, 0), (384, 192, 512),
                                        texture=WALL, floor_texture=FLOOR))
    # The ledge: a block filling the east half up to z=256.
    fx.world_brushes.append(Box((128, -192, 0), (384, 192, 256), texture=FLOOR))
    keys = [("height", "248"), ("speed", "100"), ("lip", "8")]
    if targetname:
        keys.append(("targetname", targetname))
    fx.entities = [
        Entity("func_plat", keys=keys,
               brushes=[Box((16, -48, 248), (112, 48, 256), texture=FLOOR)]),
        _spawn(-256, 0, 32),
        _spawn(300, 0, 288),
    ]
    return fx


def lift(path: Path) -> None:
    """A lift anyone can ride. The ledge is reachable and the gate must pass."""
    fx = _room_with_a_lift("reach_lift", None)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def lift_broken(path: Path) -> None:
    """The same lift with a targetname nothing fires. It sits at the top for
    ever: a deck at the height of the ledge that nobody on the floor can reach
    and nobody can call down."""
    fx = _room_with_a_lift("reach_lift_broken", "no_such_button")
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a route that exists only by teleporter
# --------------------------------------------------------------------------

def _pit_with_a_teleporter(name: str, with_destination: bool) -> MapFixture:
    fx = MapFixture(name, "a pit whose only way out is a teleporter")
    fx.world_brushes = list(hollow_room((-448, -320, -192), (448, 320, 256),
                                        texture=WALL, floor_texture=FLOOR))
    fx.world_brushes += _floor_with_hole(-448, -320, 448, 320,
                                         -96, -96, 96, 96, -192, 0)
    fx.entities = [
        Entity("trigger_teleport", keys=[("target", "out_of_the_pit")],
               brushes=[Box((-88, -88, -192), (88, 88, -128), texture=WALL)]),
        _spawn(-320, 0, 32),
        _spawn(320, 0, 32),
    ]
    if with_destination:
        fx.entities.insert(1, Entity(
            "info_teleport_destination",
            keys=[("origin", "320 -256 32"), ("targetname", "out_of_the_pit")]))
    return fx


def teleporter(path: Path) -> None:
    """A pit with a working teleporter out. The gate must pass."""
    fx = _pit_with_a_teleporter("reach_teleporter", True)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def teleporter_nowhere(path: Path) -> None:
    """The same pit, and the destination entity is simply not in the map. The
    teleporter is there, it is named, and it goes nowhere."""
    fx = _pit_with_a_teleporter("reach_teleporter_nowhere", False)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# routes that need a particular thing a player can do
# --------------------------------------------------------------------------

def crawlspace(path: Path) -> None:
    """Two rooms joined only by a gap a standing player does not fit through.
    A player is fifty-six units tall and thirty-two ducked; the gap is forty."""
    fx = MapFixture("reach_crawlspace", "two rooms joined only by a crawlspace")
    fx.world_brushes = list(hollow_room((-512, -128, 0), (512, 128, 192),
                                        texture=WALL, floor_texture=FLOOR))
    fx.world_brushes += [
        Box((-16, -128, 0), (16, -48, 192), texture=WALL),
        Box((-16, 48, 0), (16, 128, 192), texture=WALL),
        Box((-16, -48, 40), (16, 48, 192), texture=WALL),
    ]
    fx.entities = [_spawn(-320, 0, 32), _spawn(320, 0, 32)]
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def swim(path: Path) -> None:
    """Two rooms joined only under water: the player has to get in, swim across
    and climb out the far side."""
    fx = MapFixture("reach_swim", "two rooms joined only by a flooded channel")
    fx.world_brushes = list(hollow_room((-576, -192, -128), (576, 192, 256),
                                        texture=WALL, floor_texture=FLOOR))
    # Floors either side at z=0, open water between them.
    fx.world_brushes += [
        Box((-576, -192, -128), (-192, 192, 0), texture=FLOOR),
        Box((192, -192, -128), (576, 192, 0), texture=FLOOR),
    ]
    fx.world_brushes.append(
        Box((-192, -192, -128), (192, 192, -8), texture=WATER,
            contents=CONTENTS_WATER))
    fx.entities = [_spawn(-384, 0, 32), _spawn(384, 0, 32)]
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def _gap_over_lava(name: str, half_gap: float) -> MapFixture:
    """Two ledges over lava, separated by a gap.

    Lava below rather than floor, deliberately: a floor makes the bottom a
    place a player can reach and not leave, which is a true finding and a
    different one. With lava there the fall is terminal, and the only route
    between the two starts that the gate may count is the jump - so the case
    tests the jump and nothing else.
    """
    fx = MapFixture(name, "two ledges over lava with a gap between them")
    fx.world_brushes = list(hollow_room((-768, -192, 0), (768, 192, 384),
                                        texture=WALL, floor_texture=FLOOR))
    fx.world_brushes += [
        Box((-768, -192, 0), (-half_gap, 192, 128), texture=FLOOR),
        Box((half_gap, -192, 0), (768, 192, 128), texture=FLOOR),
        Box((-half_gap, -192, 0), (half_gap, 192, 64), texture=FLOOR,
            contents=CONTENTS_LAVA),
    ]
    fx.entities = [_spawn(-512, 0, 160), _spawn(512, 0, 160)]
    return fx


def jump_gap(path: Path) -> None:
    """Ninety-six units across. A player with a run-up clears it; one who
    jumps from a standstill does not, which is why the search runs first."""
    fx = _gap_over_lava("reach_jump_gap", 48.0)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def jump_gap_wide(path: Path) -> None:
    """Three hundred and twenty units across. Nobody clears that from a run,
    and a search that thought it could would be inventing routes."""
    fx = _gap_over_lava("reach_jump_gap_wide", 160.0)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a pickup nobody can get to
# --------------------------------------------------------------------------

def _room_with_an_item(name: str, sealed: bool) -> MapFixture:
    fx = MapFixture(name, "a room with a rocket launcher in it")
    fx.world_brushes = list(hollow_room((-448, -320, 0), (448, 320, 256),
                                        texture=WALL, floor_texture=FLOOR))
    if sealed:
        # A closed box around the item, with no way in. It is in plain sight
        # on any drawing of the level and no player will ever hold it.
        fx.world_brushes += hollow_room((16, -80, 0), (144, 80, 128),
                                        thickness=16.0, texture=WALL)
    fx.entities = [
        Entity("weapon_rocketlauncher", keys=[("origin", "80 0 24")]),
        _spawn(-320, 0, 32),
        _spawn(-320, 224, 32),
    ]
    return fx


def item_reachable(path: Path) -> None:
    """A rocket launcher standing on the floor. Under --items the gate must
    pass this, or the check is refusing things a player walks onto."""
    fx = _room_with_an_item("reach_item_reachable", False)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def item_sealed(path: Path) -> None:
    """The same rocket launcher inside a closed box. Nothing about how players
    reach EACH OTHER changes, which is why this needs its own question."""
    fx = _room_with_an_item("reach_item_sealed", True)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a weapon behind a gap too low to get through
# --------------------------------------------------------------------------

def _alcove(name: str, opening: float) -> MapFixture:
    """A chamber, and an alcove off it behind a wall with a gap in it.

    `opening` is how tall that gap is, and it is the only difference between
    the two halves: a doorway he walks through, or a slot he can see the
    weapon through and never reach. He cannot reach through it either - a
    player and a pickup are both thirty-two units wide, so no wall can stand
    between their boxes and still let them touch.
    """
    fx = MapFixture(name, "an alcove behind a gap in a wall")
    fx.world_brushes = list(hollow_room((-448, -320, 0), (448, 320, 256),
                                        texture=WALL, floor_texture=FLOOR))
    # The dividing wall at x = 128, solid but for one gap in the middle of it
    # running from the floor up to `opening`.
    fx.world_brushes.append(Box((128, -320, 0), (160, -64, 256), texture=WALL))
    fx.world_brushes.append(Box((128, 64, 0), (160, 320, 256), texture=WALL))
    fx.world_brushes.append(Box((128, -64, opening), (160, 64, 256),
                                texture=WALL))
    fx.entities = [
        Entity("weapon_rocketlauncher", keys=[("origin", "176 0 24")]),
        _spawn(-320, 0, 32),
        _spawn(-320, 224, 32),
    ]
    return fx


def alcove_open(path: Path) -> None:
    """The gap is a doorway. He walks in and picks the weapon up."""
    fx = _alcove("reach_alcove_open", 96.0)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def alcove_slot(path: Path) -> None:
    """The same alcove behind a slot eight units tall - lower than a player is
    even while ducking, and the weapon stays in plain sight. The gate must
    refuse it, and the pair is what says a hole is not a doorway."""
    fx = _alcove("reach_alcove_slot", 8.0)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a route that exists only by riding a train
# --------------------------------------------------------------------------

def _train_over_lava(name: str, blocked: bool) -> MapFixture:
    """Two ledges over lava, three hundred and twenty units apart.

    Nobody jumps that. The only way across is the platform that runs between
    them, so the map is a statement about one machine: if it cannot travel,
    the far half of the level does not exist.
    """
    fx = MapFixture(name, "two ledges over lava joined only by a train")
    fx.world_brushes = list(hollow_room((-768, -192, 0), (768, 192, 384),
                                        texture=WALL, floor_texture=FLOOR))
    fx.world_brushes += [
        # The right ledge begins where the platform ENDS, not where it stops:
        # a machine whose far stop is inside the thing it is arriving at has
        # nowhere to arrive, and the first version of this fixture was that.
        Box((-768, -192, 0), (-160, 192, 96), texture=FLOOR),
        Box((224, -192, 0), (768, 192, 96), texture=FLOOR),
        Box((-160, -192, 0), (224, 192, 64), texture=FLOOR,
            contents=CONTENTS_LAVA),
    ]
    if blocked:
        # A beam across the shaft the train runs through. Both ledges are
        # exactly where they were; the machine is what changed.
        fx.world_brushes.append(
            Box((-16, -96, 64), (16, 96, 256), texture=WALL))

    fx.entities = [
        Entity("func_train",
               keys=[("target", "corner_a"), ("speed", "100")],
               brushes=[Box((-160, -64, 80), (-96, 64, 96), texture=FLOOR)]),
        Entity("path_corner", keys=[("targetname", "corner_a"),
                                    ("target", "corner_b"),
                                    ("origin", "-160 -64 80")]),
        Entity("path_corner", keys=[("targetname", "corner_b"),
                                    ("target", "corner_a"),
                                    ("origin", "160 -64 80")]),
        _spawn(-512, 0, 128),
        _spawn(512, 0, 128),
    ]
    return fx


def train(path: Path) -> None:
    """The train runs. Both halves of the map are one place."""
    fx = _train_over_lava("reach_train", False)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def train_blocked(path: Path) -> None:
    """A beam across its path. The train is where it was, the ledges are where
    they were, and the far half of the level cannot be reached."""
    fx = _train_over_lava("reach_train_blocked", True)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a route that exists only by being thrown
# --------------------------------------------------------------------------

def _pit_with_a_push(name: str, speed: int) -> MapFixture:
    fx = MapFixture(name, "a pit whose only way out is a push volume")
    fx.world_brushes = list(hollow_room((-448, -320, -256), (448, 320, 320),
                                        texture=WALL, floor_texture=FLOOR))
    fx.world_brushes += _floor_with_hole(-448, -320, 448, 320,
                                         -96, -96, 96, 96, -256, 0)
    fx.entities = [
        Entity("trigger_push",
               keys=[("angle", "-1"), ("speed", str(speed))],
               brushes=[Box((-88, -88, -256), (88, 88, -192), texture=WALL)]),
        _spawn(-320, 0, 32),
        _spawn(320, 0, 32),
    ]
    return fx


def push(path: Path) -> None:
    """Thrown hard enough to clear the lip and land on the floor above."""
    fx = _pit_with_a_push("reach_push", 100)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def push_too_weak(path: Path) -> None:
    """The same volume, throwing a tenth as hard. It lifts him and drops him
    back in, which is a pit with a decoration in it."""
    fx = _pit_with_a_push("reach_push_too_weak", 10)
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a lift that cannot rise
# --------------------------------------------------------------------------

def lift_obstructed(path: Path) -> None:
    """The lift from the working fixture, with a beam across its shaft.

    Everything a static reading looks at is unchanged: the deck is there, the
    ledge is there, nothing targets it so anyone may ride it. It cannot move.
    """
    fx = _room_with_a_lift("reach_lift_obstructed", None)
    fx.world_brushes.append(Box((16, -48, 160), (112, 48, 192), texture=WALL))
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a chain of firings, and a chain with a link missing
# --------------------------------------------------------------------------

def _relay_chain(name: str, relay_target: str) -> MapFixture:
    fx = _two_rooms_and_a_door("reach_relay", "the_door")
    fx.name = name
    fx.entities.insert(1, Entity(
        "func_button",
        keys=[("angle", "0"), ("lip", "4"), ("speed", "40"),
              ("target", "the_relay"), ("wait", "3")],
        brushes=[Box((-320, 120, 32), (-288, 128, 64), texture=WALL)]))
    fx.entities.insert(2, Entity(
        "trigger_relay", keys=[("targetname", "the_relay"),
                               ("target", relay_target),
                               ("origin", "-320 0 32")]))
    return fx


def relay_chain(path: Path) -> None:
    """Button fires a relay, relay opens the door. Two links, both connected."""
    fx = _relay_chain("reach_relay_chain", "the_door")
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


def relay_broken(path: Path) -> None:
    """The same chain with the relay firing a name nothing answers to. Every
    entity is present and the door never opens."""
    fx = _relay_chain("reach_relay_broken", "nothing_is_called_this")
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


# --------------------------------------------------------------------------
# a frontier wide enough that the walk really does split
# --------------------------------------------------------------------------

def wide_hall(path: Path) -> None:
    """A pillared hall with machines around it.

    Every other fixture here is a narrow frontier: a few rooms, never eight
    states in a level, and the walk stays on one thread however many workers it
    is given. So the whole sequential-against-parallel matrix was, on all of
    them, one thread agreeing with one thread.

    A grid of pillars is the cheapest wide frontier there is - from anywhere
    inside it the search can go many ways at once - and the machines around the
    edge put movers, a teleporter and items into what the threads share.
    """
    fx = MapFixture("reach_wide_hall",
                    "a pillared hall, wide enough to walk in parallel")

    HALF, TOP, T = 768, 320, 16

    # The hall, without its east wall: that side is built by hand below,
    # because it needs a doorway in it.
    fx.world_brushes = list(hollow_room((-HALF, -HALF, 0), (HALF, HALF, TOP),
                                        texture=WALL, floor_texture=FLOOR,
                                        omit="east"))

    # Twenty-five pillars on a 256-unit grid, each 64 across. They divide the
    # floor into a lattice of ways round, which is what makes the frontier
    # wide, and they run floor to ceiling so each one is a real obstacle.
    for gx in range(-2, 3):
        for gy in range(-2, 3):
            cx, cy = gx * 256, gy * 256
            fx.world_brushes.append(Box((cx - 32, cy - 32, 0),
                                        (cx + 32, cy + 32, TOP),
                                        texture=WALL))

    # The east wall, with a doorway 128 wide and 96 tall, and the side room
    # behind it. The room's own west slab is omitted: this wall IS it.
    fx.world_brushes += [
        Box((HALF, -HALF - T, 0), (HALF + T, -64, TOP), texture=WALL),
        Box((HALF, 64, 0), (HALF + T, HALF + T, TOP), texture=WALL),
        Box((HALF, -64, 96), (HALF + T, 64, TOP), texture=WALL),
    ]
    fx.world_brushes += list(hollow_room((HALF + T, -192, 0),
                                         (HALF + T + 384, 192, TOP),
                                         texture=WALL, floor_texture=FLOOR,
                                         omit="west"))

    fx.entities = [
        _spawn(-640, -640, 32),
        _spawn(640, 640, 32),
        _spawn(-640, 640, 32),
        _spawn(640, -640, 32),
        # A door that only a button opens, so a mover round is part of what
        # the threads are working on rather than a footnote.
        Entity("func_door",
               keys=[("angle", "-1"), ("lip", "8"), ("speed", "100"),
                     ("targetname", "hall_door")],
               brushes=[Box((HALF, -64, 0), (HALF + T, 64, 96),
                            texture=WALL)]),
        Entity("func_button",
               keys=[("angle", "0"), ("lip", "4"), ("speed", "40"),
                     ("target", "hall_door"), ("wait", "3")],
               brushes=[Box((-HALF, 480, 32), (-HALF + 8, 512, 64),
                            texture=WALL)]),
        # A second kind of machine.
        #
        # Drawn at the TOP of its travel, which is where Q2 spawns a plat: a
        # plat with nothing targeting it drops to `height` below where it was
        # drawn and waits there for a rider. Drawn on the floor it would rest
        # inside the floor slab, be obstructed for its whole travel, and count
        # as a machine nothing can operate - which is exactly what the gate
        # said the first time this fixture was walked.
        Entity("func_plat",
               keys=[("speed", "80"), ("height", "128")],
               brushes=[Box((-160, -160, 128), (-96, -96, 144),
                            texture=WALL)]),
        # And a way across the hall that is not walking.
        Entity("trigger_teleport", keys=[("target", "hall_exit")],
               brushes=[Box((-704, -32, 0), (-640, 32, 64), texture=WALL)]),
        Entity("info_teleport_destination",
               keys=[("origin", "704 0 32"), ("targetname", "hall_exit")]),
        Entity("item_health", keys=[("origin", "-384 -384 32")]),
        Entity("item_health", keys=[("origin", "384 384 32")]),
        Entity("item_armor_body", keys=[("origin", "-384 384 32")]),
        Entity("weapon_rocketlauncher", keys=[("origin", "384 -384 32")]),
        Entity("light", keys=[("origin", "0 0 280"), ("light", "500")]),
    ]
    path.write_text(fx.emit(), encoding="ascii", newline="\n")


FIXTURES = {
    "wide_hall": wide_hall,
    "open_room": open_room,
    "step_down": step_down,
    "pocket": pocket,
    "lava_pit": lava_pit,
    "split": split,
    "door": door,
    "door_locked": door_locked,
    "door_button": door_button,
    "lift": lift,
    "lift_broken": lift_broken,
    "teleporter": teleporter,
    "teleporter_nowhere": teleporter_nowhere,
    "crawlspace": crawlspace,
    "swim": swim,
    "jump_gap": jump_gap,
    "jump_gap_wide": jump_gap_wide,
    "item_reachable": item_reachable,
    "item_sealed": item_sealed,
    "train": train,
    "train_blocked": train_blocked,
    "push": push,
    "push_too_weak": push_too_weak,
    "lift_obstructed": lift_obstructed,
    "relay_chain": relay_chain,
    "relay_broken": relay_broken,
    "alcove_open": alcove_open,
    "alcove_slot": alcove_slot,
    "cupboard": cupboard,
    "cupboard_dead": cupboard_dead,
}

# What the gate must say about each. True means every start reaches every
# other and nothing non-lethal is one-way.
EXPECTED = {
    # A sound level: four spawns in one component, every item reachable, the
    # door openable by the button that fires it, and no machine left that
    # nothing can work. Measured: OK, 2352 states, 9 levels of which 7 reach
    # the width at which the walk splits, 3 movers and none inoperable.
    "wide_hall": True,
    "open_room": True,
    "step_down": True,
    "pocket": False,
    "lava_pit": True,
    "split": False,
    "door": True,
    "door_locked": False,
    "door_button": True,
    "lift": True,
    "lift_broken": False,
    "teleporter": True,
    "teleporter_nowhere": False,
    "crawlspace": True,
    "swim": True,
    "jump_gap": True,
    "jump_gap_wide": False,
    "item_reachable": True,
    "item_sealed": False,
    "train": True,
    "train_blocked": False,
    "push": True,
    "push_too_weak": False,
    "lift_obstructed": False,
    "relay_chain": True,
    "relay_broken": False,
    "alcove_open": True,
    "alcove_slot": False,
    "cupboard": True,
    "cupboard_dead": False,
}


def write_all(directory: Path) -> dict[str, Path]:
    directory.mkdir(parents=True, exist_ok=True)
    out = {}
    for name, make in FIXTURES.items():
        target = directory / f"{name}.map"
        make(target)
        out[name] = target
    return out


if __name__ == "__main__":
    where = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")
    for name, target in write_all(where).items():
        print(f"{name:22s} {target}")
